local math = require('libs.math')
local nan, inf = 0 / 0, 1 / 0
local min_value = math.min_normal
local approxeqrel = math.approxeqrel

describe('ext_math.approxeqrel', function()
	spec('((64 ^ (1 / 3), 4)', function()
		assert.truthy(approxeqrel((64 ^ (1 / 3)), 4))
	end)
	spec('(1, 1)', function()
		assert.truthy(approxeqrel(1, 1))
	end)
	spec('(1, 0)', function()
		assert.falsy(approxeqrel(1, 0))
	end)
	spec('(1, nan)', function()
		assert.falsy(approxeqrel(1, nan))
	end)
	spec('(nan, nan)', function()
		assert.falsy(approxeqrel(nan, nan))
	end)
	spec('(inf, inf)', function()
		assert.truthy(approxeqrel(inf, inf))
	end)
	spec('(+/-math.min_normal, +/-math.min_normal)', function()
		assert.truthy(approxeqrel(min_value, min_value))
		assert.truthy(approxeqrel(-min_value, -min_value))
	end)
end)
